#!/usr/bin/env node

require('shelljs/global');
var shared = require('./shared');

config.verbose = false;
config.fatal = true;


echo(["  ╔══════════════════════════════════════════╗",
    "  ║                                          ║",
    "  ║          DuckieTV BuildBot               ║",
    "  ║                                          ║",
    "  ╚══════════════════════════════════════════╝"
].join("\n"));

var program = require('commander');

if (!which('git')) {
    echo('Git is required to run the DuckieTV BuildBot.');
    exit(1);
}



program
    .version('1.0.0')
    .option('-v, --verbose', 'increase verbosity')
    .command('tag-release', 'create a new (nightly) tag and push it to the repository')
    .command('prepare', 'prepare (nightly) builds for [platforms]')
    .command('make-binaries', 'create (nightly) binaries for [platforms]')
    .command('package-binaries', 'package (nightly) binaries for [platforms] into installers')
    .command('publish', 'upload packaged (nightly) installers to the github release on [tag] and to the chrome web store')
    .command('oauth-init', 'Open a web browser to grab an oAuth access token for the webstore api and store initial tokens')
    .parse(process.argv);


if (!process.argv.slice(2).length) {
    program.outputHelp();
}